site_name: Walker Booth's Website
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
repo_url: https://github.com/walkbooth/resume
docs_dir: docs
nav:
- Resume: index.md